repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: uv run format
        language: system
        pass_filenames: false
        stages: [commit]
        always_run: true